# Generated by Django 4.1.7 on 2024-04-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofilemodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='height',
            field=models.DecimalField(decimal_places=2, default='Height', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='weight',
            field=models.DecimalField(decimal_places=2, default='Weight', max_digits=5),
        ),
    ]
