# Generated by Django 5.0.3 on 2024-03-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExerciseModel",
            fields=[
                ("exercise_id", models.IntegerField(primary_key=True, serialize=False)),
                ("exercise_name", models.CharField(max_length=25)),
                ("calories_burned_per_hour", models.IntegerField()),
            ],
        ),
    ]
