# Generated by Django 5.0.3 on 2024-03-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodModel",
            fields=[
                ("food_id", models.IntegerField(primary_key=True, serialize=False)),
                ("food_name", models.CharField(max_length=25)),
                ("calories_per_serving", models.IntegerField()),
                ("protein_per_serving", models.IntegerField()),
                ("fat_per_serving", models.IntegerField()),
                ("carbs_per_serving", models.IntegerField()),
            ],
        ),
    ]
