# Generated by Django 5.0.3 on 2024-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="body",
            field=models.TextField(max_length=1000),
        ),
    ]
