# Generated by Django 5.0.3 on 2024-03-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exercise", "0001_initial"),
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseDone",
            fields=[
                (
                    "user_exercise",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("duration", models.IntegerField()),
                ("workout_date", models.DateTimeField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="exercise.exercisemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodConsumed",
            fields=[
                ("user_food", models.IntegerField(primary_key=True, serialize=False)),
                ("servings", models.IntegerField()),
                ("consumed_date", models.DateTimeField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="food.foodmodel",
                    ),
                ),
            ],
        ),
    ]
