# Generated by Django 5.0.3 on 2024-04-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myactivity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodconsumed',
            name='model',
        ),
        migrations.DeleteModel(
            name='ExerciseDone',
        ),
        migrations.DeleteModel(
            name='FoodConsumed',
        ),
    ]
